### ISSUE TITLE
等待中

### ISSUE THREAD

**Issue by 86096960** [xiaohucode/yidaRule#3]
新版什么时候能更新

**Comment by xiaohucode** [comment]
> 新版什么时候能更新
不要乱开issues。

**Comment by 86096960** [comment]
好的，达哥





------------------ 原始邮件 ------------------
发件人: dapaozhang ***@***.***&gt;
发送时间: 2023年6月8日 18:40
收件人: xiaohucode/yidaRule ***@***.***&gt;
抄送: 86096960 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xiaohucode/yidaRule] 等待中 (Issue #3)





  
新版什么时候能更新
 不要乱开issues。
