### ISSUE TITLE
新版什么时候发？

### ISSUE THREAD

**Issue by 86096960** [xiaohucode/yidaRule#5]
之前提的建议里忘了我的页面下划线不居中的问题，补上，顺便问下，什么时候更新新版呢，大佬雄起，让益达项目跑起来！加油！

**Comment by xiaohucode** [comment]
> 之前提的建议里忘了我的页面下划线不居中的问题，补上，顺便问下，什么时候更新新版呢，大佬雄起，让益达项目跑起来！加油！

端午节更新，最近头疼没精力写
